# Generated by Django 6.0.5 on 2026-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, unique=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='When quantity falls to or below this number, the item is low on stock.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='inventory_quantity_non_negative')],
            },
        ),
    ]
